/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Signer, utils } from "ethers";
import { Provider } from "@ethersproject/providers";
import type { IExecutor, IExecutorInterface } from "../IExecutor";

const _abi = [
  {
    anonymous: false,
    inputs: [
      {
        indexed: true,
        internalType: "uint32",
        name: "blockNumber",
        type: "uint32",
      },
    ],
    name: "BlockCommit",
    type: "event",
  },
  {
    anonymous: false,
    inputs: [
      {
        indexed: true,
        internalType: "uint32",
        name: "blockNumber",
        type: "uint32",
      },
    ],
    name: "BlockExecution",
    type: "event",
  },
  {
    anonymous: false,
    inputs: [
      {
        indexed: false,
        internalType: "uint32",
        name: "totalBlocksVerified",
        type: "uint32",
      },
      {
        indexed: false,
        internalType: "uint32",
        name: "totalBlocksCommitted",
        type: "uint32",
      },
    ],
    name: "BlocksRevert",
    type: "event",
  },
  {
    anonymous: false,
    inputs: [
      {
        indexed: false,
        internalType: "uint32",
        name: "expirationBlock",
        type: "uint32",
      },
      {
        indexed: false,
        internalType: "uint64[]",
        name: "operationIDs",
        type: "uint64[]",
      },
      {
        indexed: false,
        internalType: "enum Operations.OpTree",
        name: "opTree",
        type: "uint8",
      },
    ],
    name: "MovePriorityOperationsFromBufferToHeap",
    type: "event",
  },
  {
    inputs: [
      {
        components: [
          {
            internalType: "uint32",
            name: "blockNumber",
            type: "uint32",
          },
          {
            internalType: "uint16",
            name: "numberOfLayer1Txs",
            type: "uint16",
          },
          {
            internalType: "uint16",
            name: "numberOfLayer2Txs",
            type: "uint16",
          },
          {
            internalType: "uint224",
            name: "priorityOperationsComplexity",
            type: "uint224",
          },
          {
            internalType: "bytes32",
            name: "processableOnchainOperationsHash",
            type: "bytes32",
          },
          {
            internalType: "bytes32",
            name: "priorityOperationsHash",
            type: "bytes32",
          },
          {
            internalType: "uint256",
            name: "timestamp",
            type: "uint256",
          },
          {
            internalType: "bytes32",
            name: "stateRoot",
            type: "bytes32",
          },
          {
            internalType: "bytes32",
            name: "zkPorterRoot",
            type: "bytes32",
          },
          {
            internalType: "bytes32",
            name: "commitment",
            type: "bytes32",
          },
        ],
        internalType: "struct IExecutor.StoredBlockInfo",
        name: "_lastCommittedBlockData",
        type: "tuple",
      },
      {
        components: [
          {
            internalType: "bytes32",
            name: "newStateRoot",
            type: "bytes32",
          },
          {
            internalType: "bytes32",
            name: "zkPorterRoot",
            type: "bytes32",
          },
          {
            internalType: "uint32",
            name: "blockNumber",
            type: "uint32",
          },
          {
            internalType: "address",
            name: "feeAccount",
            type: "address",
          },
          {
            internalType: "uint256",
            name: "timestamp",
            type: "uint256",
          },
          {
            internalType: "uint224",
            name: "priorityOperationsComplexity",
            type: "uint224",
          },
          {
            internalType: "uint16",
            name: "numberOfLayer1Txs",
            type: "uint16",
          },
          {
            internalType: "uint16",
            name: "numberOfLayer2Txs",
            type: "uint16",
          },
          {
            internalType: "bytes32",
            name: "processableOnchainOperationsHash",
            type: "bytes32",
          },
          {
            internalType: "bytes32",
            name: "priorityOperationsHash",
            type: "bytes32",
          },
          {
            internalType: "bytes",
            name: "deployedContracts",
            type: "bytes",
          },
          {
            internalType: "bytes",
            name: "storageUpdateLogs",
            type: "bytes",
          },
          {
            components: [
              {
                internalType: "uint32",
                name: "round",
                type: "uint32",
              },
              {
                components: [
                  {
                    internalType: "bytes",
                    name: "pubkey",
                    type: "bytes",
                  },
                  {
                    internalType: "bytes",
                    name: "signature",
                    type: "bytes",
                  },
                ],
                internalType: "struct IExecutor.PublicWithSignature[]",
                name: "sigs",
                type: "tuple[]",
              },
              {
                internalType: "uint32",
                name: "stake",
                type: "uint32",
              },
            ],
            internalType: "struct IExecutor.QuorumSigs",
            name: "zkPorterData",
            type: "tuple",
          },
        ],
        internalType: "struct IExecutor.CommitBlockInfo[]",
        name: "_newBlocksData",
        type: "tuple[]",
      },
    ],
    name: "commitBlocks",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      {
        components: [
          {
            components: [
              {
                internalType: "uint32",
                name: "blockNumber",
                type: "uint32",
              },
              {
                internalType: "uint16",
                name: "numberOfLayer1Txs",
                type: "uint16",
              },
              {
                internalType: "uint16",
                name: "numberOfLayer2Txs",
                type: "uint16",
              },
              {
                internalType: "uint224",
                name: "priorityOperationsComplexity",
                type: "uint224",
              },
              {
                internalType: "bytes32",
                name: "processableOnchainOperationsHash",
                type: "bytes32",
              },
              {
                internalType: "bytes32",
                name: "priorityOperationsHash",
                type: "bytes32",
              },
              {
                internalType: "uint256",
                name: "timestamp",
                type: "uint256",
              },
              {
                internalType: "bytes32",
                name: "stateRoot",
                type: "bytes32",
              },
              {
                internalType: "bytes32",
                name: "zkPorterRoot",
                type: "bytes32",
              },
              {
                internalType: "bytes32",
                name: "commitment",
                type: "bytes32",
              },
            ],
            internalType: "struct IExecutor.StoredBlockInfo",
            name: "storedBlock",
            type: "tuple",
          },
          {
            internalType: "bytes",
            name: "processableOnchainOperations",
            type: "bytes",
          },
        ],
        internalType: "struct IExecutor.ExecuteBlockInfo[]",
        name: "_blocksData",
        type: "tuple[]",
      },
    ],
    name: "executeBlocks",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "uint256",
        name: "_nOpsToMove",
        type: "uint256",
      },
      {
        internalType: "enum Operations.OpTree",
        name: "_opTree",
        type: "uint8",
      },
    ],
    name: "movePriorityOpsFromBufferToMainQueue",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      {
        components: [
          {
            internalType: "uint32",
            name: "blockNumber",
            type: "uint32",
          },
          {
            internalType: "uint16",
            name: "numberOfLayer1Txs",
            type: "uint16",
          },
          {
            internalType: "uint16",
            name: "numberOfLayer2Txs",
            type: "uint16",
          },
          {
            internalType: "uint224",
            name: "priorityOperationsComplexity",
            type: "uint224",
          },
          {
            internalType: "bytes32",
            name: "processableOnchainOperationsHash",
            type: "bytes32",
          },
          {
            internalType: "bytes32",
            name: "priorityOperationsHash",
            type: "bytes32",
          },
          {
            internalType: "uint256",
            name: "timestamp",
            type: "uint256",
          },
          {
            internalType: "bytes32",
            name: "stateRoot",
            type: "bytes32",
          },
          {
            internalType: "bytes32",
            name: "zkPorterRoot",
            type: "bytes32",
          },
          {
            internalType: "bytes32",
            name: "commitment",
            type: "bytes32",
          },
        ],
        internalType: "struct IExecutor.StoredBlockInfo[]",
        name: "_committedBlocks",
        type: "tuple[]",
      },
      {
        components: [
          {
            internalType: "uint256[]",
            name: "recursiveInput",
            type: "uint256[]",
          },
          {
            internalType: "uint256[]",
            name: "proof",
            type: "uint256[]",
          },
          {
            internalType: "uint256[]",
            name: "commitments",
            type: "uint256[]",
          },
          {
            internalType: "uint8[]",
            name: "vkIndexes",
            type: "uint8[]",
          },
          {
            internalType: "uint256[16]",
            name: "subproofsLimbs",
            type: "uint256[16]",
          },
        ],
        internalType: "struct IExecutor.ProofInput",
        name: "_proof",
        type: "tuple",
      },
    ],
    name: "proveBlocks",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "uint32",
        name: "_blocksToRevert",
        type: "uint32",
      },
    ],
    name: "revertBlocks",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
];

export class IExecutor__factory {
  static readonly abi = _abi;
  static createInterface(): IExecutorInterface {
    return new utils.Interface(_abi) as IExecutorInterface;
  }
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): IExecutor {
    return new Contract(address, _abi, signerOrProvider) as IExecutor;
  }
}
